# Site Settings
title: Megazone DSG Blog
display_name: 메가존 DSG 테크블로그
email: seungpilpark@mz.co.kr
description: 메가존 DSG 인원들의 블로그 사이트
disqus_username: megazone-tech-blog-1
twitter_username:



remote_theme : thiagorossener/jekflix-template
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://megazonedsg.github.io" # the base hostname & protocol for your site
google_analytics: ""

# User Settings
authors:
  seungpilpark:
    name: 박승필
    description: 배우는걸 좋아하는 사람입니다.
    avatar: "/assets/img/authors/seungpilpark.jpeg"
    email: seungpilpark@mz.co.kr
    github_username: SeungpilPark
    facebook_username: mz.sppark
  soda1127:
    name: 이기정
    description: 사회공헌을 위한 개발을 좋아합니다. 최근엔 안드로이드 플랫폼을 기반으로하는 Reactive Programing에 관심이 많습니다.
    avatar: "https://i.imgur.com/oGENDcZ.jpg"
    email: dlrlwjd1127@naver.com
    github_username: SODA1127
    facebook_username: soda1127
  sondayeon:
    name: 손다연
    description: 사회공헌을 위한 개발을 좋아합니다. Cloud Native 개발자를 목표로 트레이닝 중입니다.
    avatar: ""
    email: sondayeon@mz.co.kr
    github_username: it-dayeon
    facebook_username:
  byeongcheonmun:
    name: 문병천
    description: 그냥저냥 이것저것 모아두는 습성을 가졌습니다.
    avatar: ""
    email: munbc@mz.co.kr
    github_username: munbc8308
    facebook_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
