name: Megazone DSG Blog
title: Megazone DSG Blog
description: Megazone DSG Blog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: youremail@xyz.com
disqus_username: disqus_username
show_hero: true
